services:
  postgres:
    image: postgres:16-alpine
    container_name: expense_tracker_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_tracker
    ports:
      - '5433:5432'
    volumes:
      - expense_tracker_postgres:/var/lib/postgresql/data
# TODO: Seperate development, testing and production env
  postgres_test:
    image: postgres:16-alpine
    container_name: expense_tracker_postgres_test
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_tracker_test
    ports:
      - '5434:5432'
    volumes:
      - expense_tracker_postgres_test:/var/lib/postgresql/data

volumes:
  expense_tracker_postgres:
  expense_tracker_postgres_test:
